version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - "dynamodb-local-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
  dynamodb-local-data:
    name: dynamodb-data
    external: true
